<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
        $IP = MW_INSTALL_PATH;
} else {
        $IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

// cache type to try to stop depending on spotty mysql 
//$wgParserCacheType = CACHE_NONE;

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
        if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
                die( "This script must be run from the command line\n" );
        }
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "TI3Wiki.org";

$wgLogo             = "http://www.ti3wiki.org/images/TI3logo.png";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
$wgScriptPath       = "";
$wgScriptExtension  = ".php";
$wgArticlePath = "/wiki/$1";
$wgUsePathInfo = true;

## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL

$wgEnableEmail      = true;
$wgEnableUserEmail  = true;

$wgEmergencyContact = "lance.gatlin@yahoo.com";
$wgPasswordSender = "admin@ti3wiki.org";

## For a detailed description of the following switches see
## http://www.mediawiki.org/wiki/Extension:Email_notification 
## and http://www.mediawiki.org/wiki/Extension:Email_notification
## There are many more options for fine tuning available see
## /includes/DefaultSettings.php
## UPO means: this is also a user preference option
$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

$wgDBtype           = "mysql";
require_once('LocalSettings.db.pwd');

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "TYPE=InnoDB";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

# Postgres specific settings
$wgDBport           = "5432";
$wgDBmwschema       = "mediawiki";
$wgDBts2schema      = "public";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageResize = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgMaxImageArea = 1.6e7;
$wgAllowCopyUploads = true;
$wgMaxShellMemory = 524288;
$wgUploadSizeWarning = 1024 * 1024 * 50;
$wgUploadMaxUploadSize = 1024 * 1024 * 150;

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "en";

$wgProxyKey = "204a68c0fde054cd9089f9b935420a1f8da4615bd69634bc48eb078aa3ac5170";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'monobook';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "http://www.gnu.org/copyleft/fdl.html";
$wgRightsText = "GNU Free Documentation License 1.2";
$wgRightsIcon = "${wgScriptPath}/skins/common/images/gnu-fdl.png";
# $wgRightsCode = "gfdl"; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$configdate = gmdate( 'YmdHis', @filemtime( __FILE__ ) );
$wgCacheEpoch = max( $wgCacheEpoch, $configdate );
$wgFileExtensions = array( 'bmp', 'png', 'gif', 'jpg', 'jpeg', 'wav', 'pdf', 'doc', 'xls', 'ppt', 'zip' );
$wgMimeDetectorCommand = "file -bi";

$wgUseFileCache = true; /* default: false */ 
$wgFileCacheDirectory = "$IP/cache"; 
$wgShowIPinHeader = false; 
$wgDisableCounters = true; 

$wgExtraNamespace = array();

$wgGroupPermissions['*']['edit'] = false; # Prevent anon users from editting
$wgShowIPinHeader = false; # For non-logged in users; Removes link to talk page for for non-logged in users
$wgEmailConfirmToEdit = true;
$wgAllowExternalImages = true;

$wgEnableScaryTranscluding = true;

$wgShowExceptionDetails = true;

$wgReadOnly = true;

# START DEBUG SETTINGS

$wgShowExceptionDetails = true;
$wgShowSQLErrors = true;
$wgDebugDumpSql  = true;
$wgDebugLogFile ='ti3wiki.log';

/** Only record profiling info for pages that took longer than this */
#$wgProfileLimit = 0.0;
/** Don't put non-profiling info into log file */
#$wgProfileOnly = false;
/** Log sums from profiling into "profiling" table in db. */
#$wgProfileToDatabase = false;
/** If true, print a raw call tree instead of per-function report */
#$wgProfileCallTree = false;
/** Should application server host be put into profiling table */
#$wgProfilePerHost = false;

/** Settings for UDP profiler */
#$wgUDPProfilerHost = '127.0.0.1';
#$wgUDPProfilerPort = '3811';

/** Detects non-matching wfProfileIn/wfProfileOut calls */
#$wgDebugProfiling = false;
/** Output debug message on every wfProfileIn/wfProfileOut */
#$wgDebugFunctionEntry = 0;
/** Lots of debugging output from SquidUpdate.php */
#$wgDebugSquid = false;

# Disable account creation
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['sysop']['createaccount'] = true;

require_once( 'extensions/extensions.php' );
?>